### ISSUE TITLE
OSError: Unable to parse NCBI response

### ISSUE THREAD

**Issue by GaoSpark** [gamcil/cblaster#104]

**Comment by GaoSpark** [comment]
when i install the clbaster, i meet a bug :
Traceback (most recent call last):
  File "/home/gaoyan/.local/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/home/gaoyan/.local/lib/python3.9/site-packages/cblaster/main.py", line 434, in main
    cblaster(
  File "/home/gaoyan/.local/lib/python3.9/site-packages/cblaster/main.py", line 320, in cblaster
    rid, results = remote.search(
  File "/home/gaoyan/.local/lib/python3.9/site-packages/cblaster/remote.py", line 354, in search
    rid, rtoe = start(
  File "/home/gaoyan/.local/lib/python3.9/site-packages/cblaster/remote.py", line 138, in start
    raise IOError('Unable to parse NCBI response')
OSError: Unable to parse NCBI response

**Comment by FranCanalejo** [comment]
I have exactly the same issue. 
I'm using python 3.7 and cblaster 1.3.18.
Is it an error communication with the NCBI server?

**Comment by fma91** [comment]
I'm looking for the solution of this issue too.
The versions I use are:
python3.7
cblaster1.318
Thanks

**Comment by mthang** [comment]
I had exactly the same issue, but it was due the nucleotide sequences that I used in my fasta file.
