### ISSUE TITLE
error with extract_clusters

### ISSUE THREAD

**Issue by corkdagga** [gamcil/cblaster#107]
Hi,

I have been trying to extract clusters from my cblaster search. Many of the BGCs extract correctly but I often run into into the error:

Traceback (most recent call last):
  File "/home/lab/miniconda3/bin/cblaster", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lab/miniconda3/lib/python3.12/site-packages/cblaster/main.py", line 508, in main
    extract_clusters.extract_clusters(
  File "/home/lab/miniconda3/lib/python3.12/site-packages/cblaster/extract_clusters.py", line 462, in extract_clusters
    create_genbanks_from_clusters(
  File "/home/lab/miniconda3/lib/python3.12/site-packages/cblaster/extract_clusters.py", line 174, in create_genbanks_from_clusters
    record = cluster_to_record(
             ^^^^^^^^^^^^^^^^^^
  File "/home/lab/miniconda3/lib/python3.12/site-packages/cblaster/extract_clusters.py", line 394, in cluster_to_record
    if location.start == 0 or location.end == record.location.end or "*" in cds_feature.qualifiers["translation"]:
                                              ^^^^^^^^^^^^^^^
AttributeError: 'SeqRecord' object has no attribute 'location'

This happens with several different accession numbers but I have a feeling it might be a problem with the NCBI side?

Hope you can help!

EDIT: I am using version cblaster 1.3.19 on linux and I installed using pip

**Comment by corkdagga** [comment]
A small update: I do not seem to have the problem with cblaster version 1.18.3

**Comment by gamcil** [comment]
This is likely a bug I introduced in the newer version. Do you remember which file you used as input here and/or the session file?
