### ISSUE TITLE
Repeated failure of search at results retrieving stage:

### ISSUE THREAD

**Issue by jarnie58** [gamcil/cblaster#108]
Repeated failure of search at results retrieving stage:
S C:\Users\jarni\OneDrive - O365 Turun yliopisto\Documents\Dec18> cblaster search -qf .\modifiers_pseudocluster_dec18.fasta -p plot.html -s session.json
Importing genomicsqlite failed, falling back to SQLite3
[09:17:46] INFO - Starting cblaster in remote mode
[09:17:46] INFO - Launching new search
[09:17:47] INFO - Request Identifier (RID): 89V8A7H5013
[09:17:47] INFO - Request Time Of Execution (RTOE): 22s
[09:18:09] INFO - Polling NCBI for completion status
[09:18:09] INFO - Checking search status...
[09:19:09] INFO - Checking search status...
[09:20:09] INFO - Checking search status...
[09:21:09] INFO - Checking search status...
[09:22:09] INFO - Checking search status...
[09:23:09] INFO - Checking search status...
[09:24:09] INFO - Checking search status...
[09:25:09] INFO - Checking search status...
[09:26:09] INFO - Checking search status...
[09:26:11] INFO - Search has completed successfully!
[09:26:11] INFO - Retrieving results for search 89V8A7H5013
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jarni\AppData\Local\Programs\Python\Python312\Scripts\cblaster.exe\__main__.py", line 7, in <module>
  File "C:\Users\jarni\AppData\Local\Programs\Python\Python312\Lib\site-packages\cblaster\main.py", line 432, in main
    cblaster(
  File "C:\Users\jarni\AppData\Local\Programs\Python\Python312\Lib\site-packages\cblaster\main.py", line 318, in cblaster
    rid, results = remote.search(
                   ^^^^^^^^^^^^^^
  File "C:\Users\jarni\AppData\Local\Programs\Python\Python312\Lib\site-packages\cblaster\remote.py", line 371, in search
    results = retrieve(rid, hitlist_size=hitlist_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jarni\AppData\Local\Programs\Python\Python312\Lib\site-packages\cblaster\remote.py", line 209, in retrieve
    .group(1)
     ^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
PS C:\Users\jarni\OneDrive - O365 Turun yliopisto\Documents\Dec18>

**Comment by Rene-Hoover** [comment]
I'm not sure if this can help you or other folks investigating the issue, but I received the same error for 1 of 2 query files I was analyzing. This let me trouble shoot my files and when I compared my input it seemed like having a blank line in between the sequences was the problem. 

For example, the file with spaces between:
```
>fasta-header-1
MSINYKEVINDLRTQLGDRPVTD

>fasta-header-2
RAAGTSLSGQAIGEGILLILGHDGFRKIEVSS

>fasta-header-3
ALAERIRKKYSIKNTTGYGINS
```
Did not work, but if I removed the spaces between lines like so:
```
>fasta-header-1
MSINYKEVINDLRTQLGDRPVTD
>fasta-header-2
RAAGTSLSGQAIGEGILLILGHDGFRKIEVSS
>fasta-header-3
ALAERIRKKYSIKNTTGYGINS
```
It ran without error. 

I'm just a user, but this is what worked for me. Cheers!

**Comment by gamcil** [comment]
This should be fixed with 85435f6bd9a6fa20a6bbb21236b6b4db38dd454c.
