### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by corkdagga** [gamcil/cblaster#114]
Hi All,

I am a new mac user and have been slowly setting up the new laptop. I freshly installed cblaster and am running into some problems (see below). I think it could be a python issue. I was using zsh but after installing everything, I changed to bash, then tried to uninstall and reinstall again. I have a feeling this could be there the issue is.

NABI-MAC001:cblaster_test paul$ cblaster search -m remote --rid KV6WEC7B013 -qf myQF_9705.fasta -p test6.html
Importing genomicsqlite failed, falling back to SQLite3
[09:39:43] INFO - Starting cblaster in remote mode
[09:39:43] INFO - Polling NCBI for completion status
[09:39:43] INFO - Checking search status...
[09:39:43] INFO - Search has completed successfully!
[09:39:43] INFO - Retrieving results for search KV6WEC7B013
Traceback (most recent call last):
  File "/Users/paul/Library/Python/3.9/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/Users/paul/Library/Python/3.9/lib/python/site-packages/cblaster/main.py", line 432, in main
    cblaster(
  File "/Users/paul/Library/Python/3.9/lib/python/site-packages/cblaster/main.py", line 318, in cblaster
    rid, results = remote.search(
  File "/Users/paul/Library/Python/3.9/lib/python/site-packages/cblaster/remote.py", line 371, in search
    results = retrieve(rid, hitlist_size=hitlist_size)
  File "/Users/paul/Library/Python/3.9/lib/python/site-packages/cblaster/remote.py", line 208, in retrieve
    for line in re.search("<PRE>(.+?)</PRE>", response.text, re.DOTALL)
AttributeError: 'NoneType' object has no attribute 'group'

Any help to get cblaster working would be great! thank you :)

**Comment by corkdagga** [comment]
I also saw some other posts with the same issue, these were either fixed with an updated version or I tried the suggestions but it did not work for me... I am running the latest version.

**Comment by Clauvio** [comment]
Same problem and waiting for someone to help us

**Comment by corkdagga** [comment]
Thanks! That fix worked for me :)

**Comment by FriederikeBiermann** [comment]
I think this issue should not be closed, as the PR was not merged yet and I expect all users to be affected by this issue. It's really hard to find the connection between the issue and the PR now.

**Comment by corkdagga** [comment]
> I think this issue should not be closed, as the PR was not merged yet and I expect all users to be affected by this issue. It's really hard to find the connection between the issue and the PR now.

Sorry about that! Its re-opened.

**Comment by Dx-wmc** [comment]
@FriederikeBiermann According to the PR, I modified the corresponding two lines of code, but the error still occurs. 

```
Traceback (most recent call last):
  File "/home/data/usr/dx/miniconda3/envs/cblaster/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 432, in main
    cblaster(
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 318, in cblaster
    rid, results = remote.search(
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 373, in search
    results = retrieve(rid, hitlist_size=hitlist_size)
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 210, in retrieve
    for line in re.search("<PRE>(.+?)</PRE>", response.text, re.DOTALL)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by FriederikeBiermann** [comment]
> @FriederikeBiermann According to the PR, I modified the corresponding two lines of code, but the error still occurs.
> 
> ```
> Traceback (most recent call last):
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/bin/cblaster", line 8, in <module>
>     sys.exit(main())
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 432, in main
>     cblaster(
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 318, in cblaster
>     rid, results = remote.search(
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 373, in search
>     results = retrieve(rid, hitlist_size=hitlist_size)
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 210, in retrieve
>     for line in re.search("<PRE>(.+?)</PRE>", response.text, re.DOTALL)
> AttributeError: 'NoneType' object has no attribute 'group'
> ```

Did you make sure to install the new version to your conda env or change it directly in the /home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py?

**Comment by Dx-wmc** [comment]
Yes, I have modified the remote.py and the version of cblaster is latest 1.3.19.

**Comment by FriederikeBiermann** [comment]
> Yes, I have modified the remote.py and the version of cblaster is latest 1.3.19.

If you put in a preint statement that prints out the URL it uses to fetch, what does it show?

**Comment by Dx-wmc** [comment]
Hi, this is the output after adding the URL.
```
[11:35:19] INFO - Starting cblaster in remote mode
[11:35:19] INFO - Launching new search
Request URL (POST): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=PUT&DATABASE=nr&PROGRAM=blastp&FILTER=F&EXPECT=0.01&GAPCOSTS=11+1&MATRIX=BLOSUM62&HITLIST_SIZE=5000&ALIGNMENTS=5000&DESCRIPTIONS=5000&WORD_SIZE=6&COMPOSITION_BASED_STATISTICS=2&THRESHOLD=11
[11:35:23] INFO - Request Identifier (RID): MFT7VWSV013
[11:35:23] INFO - Request Time Of Execution (RTOE): 16s
[11:35:39] INFO - Polling NCBI for completion status
[11:35:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:36:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:37:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:38:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:39:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:40:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:41:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:42:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:43:39] INFO - Checking search status...
Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
[11:43:40] INFO - Search has completed successfully!
[11:43:40] INFO - Retrieving results for search MFT7VWSV013
Request URL (GET for retrieval): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&ALIGNMENT_VIEW=Tabular&FORMAT_OBJECT=Alignment&HITLIST_SIZE=5000&ALIGNMENTS=5000&DESCRIPTIONS=5000&FORMAT_TYPE=Text
Traceback (most recent call last):
  File "/home/data/usr/dx/miniconda3/envs/cblaster/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 432, in main
    cblaster(
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 318, in cblaster
    rid, results = remote.search(
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 374, in search
    results = retrieve(rid, hitlist_size=hitlist_size)
  File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 211, in retrieve
    for line in re.search("<PRE>(.+?)</PRE>", response.text, re.DOTALL)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by FriederikeBiermann** [comment]
> Hi, this is the output after adding the URL.
> 
> ```
> [11:35:19] INFO - Starting cblaster in remote mode
> [11:35:19] INFO - Launching new search
> Request URL (POST): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=PUT&DATABASE=nr&PROGRAM=blastp&FILTER=F&EXPECT=0.01&GAPCOSTS=11+1&MATRIX=BLOSUM62&HITLIST_SIZE=5000&ALIGNMENTS=5000&DESCRIPTIONS=5000&WORD_SIZE=6&COMPOSITION_BASED_STATISTICS=2&THRESHOLD=11
> [11:35:23] INFO - Request Identifier (RID): MFT7VWSV013
> [11:35:23] INFO - Request Time Of Execution (RTOE): 16s
> [11:35:39] INFO - Polling NCBI for completion status
> [11:35:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:36:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:37:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:38:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:39:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:40:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:41:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:42:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:43:39] INFO - Checking search status...
> Request URL (GET): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&FORMAT_OBJECT=SearchInfo
> [11:43:40] INFO - Search has completed successfully!
> [11:43:40] INFO - Retrieving results for search MFT7VWSV013
> Request URL (GET for retrieval): https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=MFT7VWSV013&ALIGNMENT_VIEW=Tabular&FORMAT_OBJECT=Alignment&HITLIST_SIZE=5000&ALIGNMENTS=5000&DESCRIPTIONS=5000&FORMAT_TYPE=Text
> Traceback (most recent call last):
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/bin/cblaster", line 8, in <module>
>     sys.exit(main())
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 432, in main
>     cblaster(
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 318, in cblaster
>     rid, results = remote.search(
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 374, in search
>     results = retrieve(rid, hitlist_size=hitlist_size)
>   File "/home/data/usr/dx/miniconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/remote.py", line 211, in retrieve
>     for line in re.search("<PRE>(.+?)</PRE>", response.text, re.DOTALL)
> AttributeError: 'NoneType' object has no attribute 'group'
> ```

Interestingly, the retrieve download link now works. Maybe you can also print the response.text?

**Comment by Tim-Kirkwood** [comment]
Hello,

Just to confirm, I had the same error following @FriederikeBiermann pr being merged into the latest version, and setting -hs to 250 from the default 500 worked for me.  Big lifesaver, thanks very much!

Cheers,
Tim

**Comment by LoganOtt** [comment]
I am encountering this same exact issue currently as well. I have checked the remote.py file and already has the fix from #115 in it already. Has the API changed yet again?
