### ISSUE TITLE
AttributeError: 'SeqRecord' object has no attribute 'location'

### ISSUE THREAD

**Issue by HuaweiHuang25** [gamcil/cblaster#117]
Hi, i am using the cbalster extract_clusters to retrieve the clusters based on the json file created by cblaster search, but the process always stop at the same sequence. can anyone hele?
[12:42:46] INFO - Querying NCBI for sequence of JBHUUM010000001.1 from 103199 to 211195
Traceback (most recent call last):
  File "/home/ntu/anaconda3/envs/cblaster/bin/cblaster", line 10, in <module>
    sys.exit(main())
  File "/home/ntu/anaconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/main.py", line 508, in main
    extract_clusters.extract_clusters(
  File "/home/ntu/anaconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/extract_clusters.py", line 462, in extract_clusters
    create_genbanks_from_clusters(
  File "/home/ntu/anaconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/extract_clusters.py", line 174, in create_genbanks_from_clusters
    record = cluster_to_record(
  File "/home/ntu/anaconda3/envs/cblaster/lib/python3.9/site-packages/cblaster/extract_clusters.py", line 394, in cluster_to_record
    if location.start == 0 or location.end == record.location.end or "*" in cds_feature.qualifiers["translation"]:
AttributeError: 'SeqRecord' object has no attribute 'location'

**Comment by Tsingsjeen** [comment]
Same issue! does this solved?

**Comment by Tsingsjeen** [comment]
Thanks! I will back to the older version. There could have codes changes in "extract_cluster" module between the old version as you mentioned and the new that is not stably applied.

Thanks a lot!

**Comment by Tsingsjeen** [comment]
Sorry to spam. I tried the v.1.3.18 and fortunately it worked.

**Comment by HuaweiHuang25** [comment]
Sorry for my mistake, I misremembered the version…
Glad to hear it worked! Good luck with your research.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
