### ISSUE TITLE
GUI search Error

### ISSUE THREAD

**Issue by Enrichmentmapmademedothis** [gamcil/cblaster#12]
After opening the cblaster gui and selecting a protein.fa file, then selecting start without changing any settings, the following error occurs

u1897925$ cblaster gui
objc[80614]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8cf893d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x121705f50). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/bin/cblaster", line 10, in <module>
    sys.exit(main())
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/lib/python3.8/site-packages/cblaster/main.py", line 322, in main
    cblaster_gui()
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/lib/python3.8/site-packages/cblaster/gui/main.py", line 168, in cblaster_gui
    window[f"summary_{key}"].update(disabled=not values["summary_gen"])
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 2159, in Update
    self.TKSpinBox['state'] = 'enable'
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1648, in __setitem__
    self.configure({key: value})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: bad state "enable": must be disabled, normal, or readonly

changing any settings (e.g. inputting a database to use), generates the same error.

current version installed was the most up to date on the 15th November

**Comment by Enrichmentmapmademedothis** [comment]
input error, not the programs fault
