### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by camilogarciabotero** [gamcil/cblaster#54]
Hi @gamcil 

Thanks for your work on this program. I was giving it a try and got an error. Here the specifications of my system and the error log.

I installed `cblaster` via `pip` after installing `diamond` as suggested in the docs. I used `python 3.8.5` and `pip 21.0.1`.
Then, I config `cblaster config '<email>'`. When running a simple remote search `cblaster -qr <name.fasta>` I got the following error:

```
Welcome to cblaster
[17:11:10] INFO - Starting cblaster in remote mode
[17:11:10] INFO - Launching new search
Traceback (most recent call last):
  File "/Applications/miniconda3/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/Applications/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 404, in main
    cblaster(
  File "/Applications/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 306, in cblaster
    rid, results = remote.search(
  File "/Applications/miniconda3/lib/python3.8/site-packages/cblaster/remote.py", line 340, in search
    rid, rtoe = start(
  File "/Applications/miniconda3/lib/python3.8/site-packages/cblaster/remote.py", line 125, in start
    rid, rtoe = re.findall(r"(?:RID|RTOE) = (.+?)[\n\s]", response.text)
ValueError: not enough values to unpack (expected 2, got 0)
``` 

If you have any thoughts on this matter I'll really appreciate them.
Thanks in advance,
Camilo.

**Comment by gamcil** [comment]
Hi Camilo,

You've done everything right - looks like the NCBI might have sent back a bad response when cblaster tried to start the search (I should put in a better error message here). Could you try the search again to see if it was just a one off?

**Comment by camilogarciabotero** [comment]
Hi @gamcil 

Thanks for the quick reply. I tried again today, same error.

**Comment by gamcil** [comment]
Hmm that's weird, can't reproduce starting a search on my end. Is it possible for you to upload your files here? (just so I can check your input is OK)

**Comment by camilogarciabotero** [comment]
Sure:

```
>EA-CB0015:3158343-3159959
TTATTTACCTAAAAGATTGATAAATTTACTCAGTTCTTCTTTGGCTTCATCTGTTGTCCC
GTTCAACTCGTTCAAAAGCCCAAACAATTTTTCATATGAATTCGTAATATCTGCTTTTAC
TTCTGTCAACTCTTGAGCCACTTGTGAAAGTGGAATAACTTCTTCTTCTTCAAACGTGTC
CACATAACGTGGAATGTTCAAATTGTAATCATTTTCTTTGATTTCATTCAAAGATGCCAC
ATGAGCATATTTCTCAACGTCTTTACGGCTACGGTAAGTTTCGATAATTTTGTTGATGTT
CTCAGCAGAGAGTTTGTTTTGGTTCTTGCCCTTTTCAAACTCATTTGAAGCATCGATAAA
TAAAACATCTTTATTCTTGCGAGCTTCACGACCTTTAAACACCAGCACACAGGTTGGGAT
GCTAGCGCCATAGAACAAGTTAGCTGGCAATCCAATAACAGTATCTAACAGATTGTTGTC
GATGATATTTTTACGGATTCTACCTTCAGACGCACCACGGAAGAGCACCCCATGAGGCAA
TACGATAGCCATAGTTCCATTTTTATCCAAATGATAAAGTCCATGCAGTACAAAAGCATA
ATCTGCCTTAGATGCAGGCGCTACACCATAACCCTTGAAACGTGTATCTTTTTCTCGATC
AACGTCTTTTGTATCCCATTTATGGGAATATGGGGGGTTTGATACGACGGCGTCGAACTT
CAAAGGAATTTGTGTGCCATCTTTTTCAGCAAATGGCCAGTCAGCATCAAGTGTGTCTGC
TCGTTTCAACTCCATATTGCGATAGTTAACCCCATGCATCATCAAGTTCATGCGGGCTAA
GTTATAAGTCGTCGTATTCAACTCTTGGCCGTAAAACTCAACGCTTCCTTCTTCATCACC
ATTTGGTAATTCTTTTTGGACTGTTAGAAGAAGTGAACCCGATCCCATTGTAGGGTCATA
AACACGGAATTGACCGCCAGTTCCATCTGCATCATTCGTGACAATTTTCGCCAGGATTTG
ACTAACTTCATGCGGTGTATAGAATTCCCCTCCTTTTTTACCAGCATTGGCAGCAAATTG
TCCAATCAAATATTCATAAACGTCACCCAAAATGTCGTGCCCTGAATCGTCTTTGAAAGT
GAACTCGTTAATCATCAACACGATATCATTCAAAGCCTTTGCACGTTCGTTTGTACTTGA
GCCAAGACGTGTGTCCCCAAGGTTAACATCTGAAAATACATTAGCAAAGTCAGCTTCTGC
AATCGCGTTACGTTTTGCATTTATATTGAATGAGTCAAACATATCTTGGAAGTCACTAGC
TTTGATTTTGTGATTTTCGATTTTTGATACGATTTTGTCCCAGGTGTAGGCTGGGTCAAT
CGCATATCCGATACCTTTACTAATTTCTTCAAGGTAATCTTCTTTTTCAGTTTCATCTGT
CACTTCGTAAAACTCTTCCAGGTCATTGACTTTTAAGTATTCATCTTGATTTTCTGATAA
ATAGCGATAAAACATAAATGGCAAAATATAGTTCTTATACTCACTTGCATCCATTGTTCC
ACGCAGTTTGTTAGCCATTCCCCATAGCTTTGATGTAATTTTCCTTGCATTACTCAT
```

**Comment by gamcil** [comment]
Ahh, you're using nucleotide sequences - cblaster internally uses BLASTp, so it expects protein translations for input. Translating your sequence to:

```
>EA-CB0015:3158343-3159959
MSNARKITSKLWGMANKLRG
TMDASEYKNYILPFMFYRYL
SENQDEYLKVNDLEEFYEVT
DETEKEDYLEEISKGIGYAI
DPAYTWDKIVSKIENHKIKA
SDFQDMFDSFNINAKRNAIA
EADFANVFSDVNLGDTRLGS
STNERAKALNDIVLMINEFT
FKDDSGHDILGDVYEYLIGQ
FAANAGKKGGEFYTPHEVSQ
ILAKIVTNDADGTGGQFRVY
DPTMGSGSLLLTVQKELPNG
DEEGSVEFYGQELNTTTYNL
ARMNLMMHGVNYRNMELKRA
DTLDADWPFAEKDGTQIPLK
FDAVVSNPPYSHKWDTKDVD
REKDTRFKGYGVAPASKADY
AFVLHGLYHLDKNGTMAIVL
PHGVLFRGASEGRIRKNIID
NNLLDTVIGLPANLFYGASI
PTCVLVFKGREARKNKDVLF
IDASNEFEKGKNQNKLSAEN
INKIIETYRSRKDVEKYAHV
ASLNEIKENDYNLNIPRYVD
TFEEEEVIPLSQVAQELTEV
KADITNSYEKLFGLLNELNG
TTDEAKEELSKFINLLGK*
```

works fine for me. Also, if you have a GenBank file for the region these sequences are from, you can use that directly (cblaster will parse out protein translations itself).

**Comment by camilogarciabotero** [comment]
Oh, @gamcil thank you so much!

Did I miss that in the docs? At least this issue will help others when getting the error message... 

Thanks again!
Camilo.

**Comment by gamcil** [comment]
Glad it's working now! Should be in the docs, if not I'll go add a note.
