### ISSUE TITLE
No configuration folder detected, please run cblaster config

### ISSUE THREAD

**Issue by zuoyang97** [gamcil/cblaster#57]
Traceback (most recent call last):
  File "/root/miniconda3/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 403, in main
    set_entrez()
  File "/root/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 42, in set_entrez
    cfg = config.get_config_parser()
  File "/root/miniconda3/lib/python3.8/site-packages/cblaster/config.py", line 20, in get_config_parser
    raise IOError("No configuration folder detected, please run cblaster config")
OSError: No configuration folder detected, please run cblaster config

**Comment by gamcil** [comment]
Run `cblaster config --email your@email.com` before trying a search to generate the necessary config files

**Comment by zuoyang97** [comment]
(base) root@LIUZUOYANG97:~# cblaster config --email liuzuoyang97@163.com
Traceback (most recent call last):
  File "/root/miniconda3/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 403, in main
    set_entrez()
  File "/root/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 42, in set_entrez
    cfg = config.get_config_parser()
  File "/root/miniconda3/lib/python3.8/site-packages/cblaster/config.py", line 20, in get_config_parser
    raise IOError("No configuration folder detected, please run cblaster config")
OSError: No configuration folder detected, please run cblaster config
# <<< conda initialize <<<
export PATH=$PATH:/root/miniconda3/bin/cblaster
export PATH=$PATH:/root/miniconda3/lib/python3.8/site-packages/cblaster/config.py

**Comment by gamcil** [comment]
Thanks, this was a bug. Should be fixed by https://github.com/gamcil/cblaster/commit/2a51cfb8c2fcdf1c46562e374c9a3893a27f0aa7 which I just pushed in v1.3.8. Could you update with `pip install --upgrade cblaster` and try again?

**Comment by zuoyang97** [comment]
I don't think that's your problem.I've run this program on a virtual machine, and it's been very useful for me.But I had some problems running the program on the server,It could be a server problem.
