### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by lydia1201** [gamcil/cblaster#60]
$ cblaster search -qf praregion1.fasta
[23:15:36] INFO - Starting cblaster in remote mode
[23:15:36] INFO - Launching new search
Traceback (most recent call last):
  File "/home/xinyu/.local/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/home/xinyu/.local/lib/python3.6/site-packages/cblaster/main.py", line 469, in main
    testing=args.testing,
  File "/home/xinyu/.local/lib/python3.6/site-packages/cblaster/main.py", line 324, in cblaster
    hitlist_size=hitlist_size,
  File "/home/xinyu/.local/lib/python3.6/site-packages/cblaster/remote.py", line 346, in search
    **kwargs
  File "/home/xinyu/.local/lib/python3.6/site-packages/cblaster/remote.py", line 125, in start
    rid, rtoe = re.findall(r"(?:RID|RTOE) = (.+?)[\n\s]", response.text)
ValueError: not enough values to unpack (expected 2, got 0)

How to solve this issue
Thank you

**Comment by lydia1201** [comment]
adjusted the input file f
