### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AKBode** [gamcil/cblaster#62]
Hi,

Any idea how to fix the error?

Thank you 

[12:48:06] INFO - Starting cblaster in remote mode
[12:48:06] INFO - Launching new search
[12:48:08] INFO - Request Identifier (RID): JEWB6TRN016
[12:48:08] INFO - Request Time Of Execution (RTOE): 28s
[12:48:36] INFO - Polling NCBI for completion status
[12:48:36] INFO - Checking search status...
[12:49:36] INFO - Checking search status...
[12:50:36] INFO - Checking search status...
[12:51:36] INFO - Checking search status...
[12:52:36] INFO - Checking search status...
[12:53:36] INFO - Checking search status...
[12:54:36] INFO - Checking search status...
[12:55:36] INFO - Checking search status...
[12:56:36] INFO - Checking search status...
[12:57:36] INFO - Checking search status...
[12:58:36] INFO - Checking search status...
[12:59:36] INFO - Checking search status...
[13:00:36] INFO - Checking search status...
[13:01:36] INFO - Checking search status...
[13:02:36] INFO - Checking search status...
[13:03:36] INFO - Checking search status...
[13:04:36] INFO - Checking search status...
[13:05:36] INFO - Checking search status...
[13:06:36] INFO - Checking search status...
[13:07:36] INFO - Checking search status...
[13:08:36] INFO - Checking search status...
[13:09:36] INFO - Checking search status...
[13:09:40] INFO - Search has completed successfully!
[13:09:40] INFO - Retrieving results for search JEWB6TRN016
[13:10:15] INFO - Parsing results...
[13:10:16] INFO - Found 32138 hits meeting score thresholds for remote search
[13:10:16] INFO - Fetching genomic context of hits
Traceback (most recent call last):
  File "/root/miniconda3/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/cblaster/main.py", line 469, in main
    testing=args.testing,
  File "/root/miniconda3/lib/python3.7/site-packages/cblaster/main.py", line 339, in cblaster
    percentage=percentage,
  File "/root/miniconda3/lib/python3.7/site-packages/cblaster/context.py", line 569, in search
    output_file=ipg_file
  File "/root/miniconda3/lib/python3.7/site-packages/cblaster/context.py", line 77, in efetch_IPGs
    lines = [line.decode() for line in fetch.readlines()]
  File "/root/miniconda3/lib/python3.7/site-packages/cblaster/context.py", line 77, in <listcomp>
    lines = [line.decode() for line in fetch.readlines()]
AttributeError: 'str' object has no attribute 'decode'

**Comment by gamcil** [comment]
Hi @AKBode, not completely sure what happened here. Looks like it got a bad response from the NCBI and cblaster didn't catch it. When this happens, usually trying again is enough to fix it - you can also reuse the RID number using the ``--rid`` argument so you don't have to repeat the entire search from scratch, e.g. ``cblaster search --rid JEWB6TRN016 -qf query.fasta``

**Comment by jcpasion** [comment]
Hello, I received a similar error after running a remote search, as well as when I researched the query using the RID number. The search was successful, so not sure what is happening on, here is the output:

```
Traceback (most recent call last):
  File "/home/xxxxx/anaconda3/envs/bigscape/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/home/xxxxx/anaconda3/envs/bigscape/lib/python3.8/site-packages/cblaster/main.py", line 429, in main
    cblaster(
  File "/home/xxxxx/anaconda3/envs/bigscape/lib/python3.8/site-packages/cblaster/main.py", line 331, in cblaster
    organisms = context.search(
  File "/home/xxxxx/anaconda3/envs/bigscape/lib/python3.8/site-packages/cblaster/context.py", line 567, in search
    rows = efetch_IPGs(
  File "/home/xxxxx/anaconda3/envs/bigscape/lib/python3.8/site-packages/cblaster/context.py", line 77, in efetch_IPGs
    lines = [line.decode() for line in fetch.readlines()]
  File "/home/xxxxx/anaconda3/envs/bigscape/lib/python3.8/site-packages/cblaster/context.py", line 77, in <listcomp>
    lines = [line.decode() for line in fetch.readlines()]
AttributeError: 'str' object has no attribute 'decode'
```
cblaster was installed inside my Bigscape conda environment. 

RID: KZMYXD18013

**Comment by jcpasion** [comment]
I actually tried a different conda environment that had cblaster installed, and it worked!
