### ISSUE TITLE
makedb issue

### ISSUE THREAD

**Issue by karenycy** [gamcil/cblaster#63]
Hi,

I have some issues when making the database, it can generate the three database files but the mydb.fasta file is empty.

Does anyone can solve this problem? Thank you!

[10:17:10] INFO - Starting makedb module
[10:17:10] INFO - Initialising cblaster SQLite3 database to mydb.sqlite3
[10:17:10] INFO - Parsing 32 genome files, in 1 batches of 32
[10:17:10] INFO - Processing batch 1
[10:17:10] INFO -   GENOME002050.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME003291.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME013732.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME016216.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME060200.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME098563.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME100143.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME101483.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME138224.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME156273.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME242796.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME262194.fna.fixed.fa.db.gff
[10:17:10] INFO -   GENOME276040.fna.fixed.fa.db.gff
[10:17:11] ERROR - File parsing failed, exiting...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/site-packages/cblaster/genome_parsers.py", line 200, in parse_file
    return dict(name=name, records=parse_gff(path))
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/site-packages/cblaster/genome_parsers.py", line 140, in parse_gff
    gff = gffutils.create_db(
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/site-packages/gffutils/create.py", line 1292, in create_db
    c.create()
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/site-packages/gffutils/create.py", line 507, in create
    self._populate_from_lines(self.iterator)
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/site-packages/gffutils/create.py", line 589, in _populate_from_lines
    self._insert(f, c)
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/site-packages/gffutils/create.py", line 530, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/site-packages/cblaster/database.py", line 204, in makedb
    for organism in pool.imap(func, group):
  File "/util/opt/anaconda/deployed-conda-envs/packages/cblaster/envs/cblaster-1.3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.
[10:17:11] INFO - Writing FASTA to mydb.fasta
[10:17:11] INFO - Building DIAMOND database at mydb.dmnd
[10:17:11] INFO - Done!

**Comment by gamcil** [comment]
Hi @karenycy, sorry for the delay. This was caused by an issue with the GFF parsing which should be fixed in the newest release (v1.3.10). Could you try updating your cblaster version and trying again?
