### ISSUE TITLE
database building error

### ISSUE THREAD

**Issue by yye88** [gamcil/cblaster#67]
[13:34:17] ERROR - File parsing failed, exiting...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/share/apps/miniconda/anaconda3-2019.10/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/genome_parsers.py", line 209, in parse_file
    for record in function()
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/genome_parsers.py", line 162, in parse_gff
    [*gene, *merge_cds_features(cds)],
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/genome_parsers.py", line 113, in merge_cds_features
    if merged[-1].qualifiers["ID"][0] == feature.qualifiers["ID"][0]:
KeyError: 'ID'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/database.py", line 204, in makedb
    for organism in pool.imap(func, group):
  File "/share/apps/miniconda/anaconda3-2019.10/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
KeyError: 'ID'
[13:34:17] INFO - Writing FASTA to myDb.fasta
[13:34:17] INFO - Building DIAMOND database at myDb.dmnd
[13:34:17] INFO - Done!

**Comment by gamcil** [comment]
Would you be able to upload any of the files you are trying to build a database from?

**Comment by yye88** [comment]
[DF.zip](https://github.com/gamcil/cblaster/files/7495304/DF.zip)
Thank you for reply. I upload a zip file containing a gff file and a coresponding fasta file. Please hava a look what went wrong. Thank you.

**Comment by gamcil** [comment]
It looks like the GFF3 produced by Augustus is missing some required fields. From a quick search, I think this is a well known issue with Augustus (https://github.com/Gaius-Augustus/Augustus/issues/74). One suggestion from that link is to use ``agat_sp_gxf_to_gff3.pl`` from AGAT (https://github.com/NBISweden/AGAT) - maybe that can fix your GFF3 file?

**Comment by yye88** [comment]
Thank you so much, I will try that for sure.
