### ISSUE TITLE
Issues with sqlite3 and initiating cblaster

### ISSUE THREAD

**Issue by pksun1** [gamcil/cblaster#79]
Hi,

I'm not very good with python, but I most definitely would like to use cblaster!  However, I've run into an issue where I can't seem to initiate the program.  Please see below the traceback logs

(myenv) C:\Users\Phillip\env\myenv\Scripts>cblaster
Traceback (most recent call last):
  File "c:\users\phillip\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\phillip\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Phillip\AppData\Local\Programs\Python\Python38\Scripts\cblaster.exe\__main__.py", line 4, in <module>
  File "c:\users\phillip\appdata\local\programs\python\python38\lib\site-packages\cblaster\main.py", line 11, in <module>
    from cblaster import (
  File "c:\users\phillip\appdata\local\programs\python\python38\lib\site-packages\cblaster\context.py", line 44, in <module>
    from cblaster import database
  File "c:\users\phillip\appdata\local\programs\python\python38\lib\site-packages\cblaster\database.py", line 9, in <module>
    import genomicsqlite
  File "c:\users\phillip\appdata\local\programs\python\python38\lib\site-packages\genomicsqlite\__init__.py", line 30, in <module>
    _MEMCONN.load_extension(_DLL)
sqlite3.OperationalError: The specified module could not be found.

Is this something off with cblaster?  or is it an error on a dependency, or another program that cblaster relies on?

I've updated sqlite3 to it's most current version as well, which would be:
>>> sqlite3.sqlite_version
'3.38.5'

Please let me know how might I address this.  I'm currently using Windows 11, 64bit.

**Comment by gamcil** [comment]
Hi @pksun1, I think the issue is an SQL related library added with the latest release (genomicsqlite). For now you could revert to an older version which should work:

`pip install --upgrade cblaster==1.3.12`

I also run into the same issue on OSX 12.4, M1 chip, using within a Conda environment. Not sure if it has something to do with Python sqlite not allowing loadable extensions, or genomicsqlite itself.. @brymerr921 Any ideas?

**Comment by pksun1** [comment]
Thank you so much!!! I've been trying to work with alternative programs but I had really wanted to utilize cblaster, now I have it running my first search!  You totally salvaged my weekend! Thanks!
