### ISSUE TITLE
not able to proceed with gne and clinker

### ISSUE THREAD

**Issue by pksun1** [gamcil/cblaster#80]
Hi, I'm using cblaster gui and command line and I keep ending up with an error with gne reading my session json file, as well as proceeding to produce my figures via clinker.  Here's the output that I get when I utilize gne module in cblaster gui:

Welcome to cblaster[01:01:20] INFO - Starting cblaster gene neighbourhood estimation[01:01:20] INFO - Loading session from: /home/phillip/session4.json[01:01:20] INFO - Computing gene neighbourhood statisticsTraceback (most recent call last):  File "/home/phillip/miniconda3/bin/cblaster", line 10, in <module>    sys.exit(main())  File "/home/phillip/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 481, in main    gne(  File "/home/phillip/miniconda3/lib/python3.8/site-packages/cblaster/main.py", line 68, in gne    results = context.estimate_neighbourhood(  File "/home/phillip/miniconda3/lib/python3.8/site-packages/cblaster/context.py", line 536, in estimate_neighbourhood    filter_session(session, gap=value)  File "/home/phillip/miniconda3/lib/python3.8/site-packages/cblaster/context.py", line 500, in filter_session    scaffold.add_clusters(clusters, query_sequence_order=session.queries)  File "/home/phillip/miniconda3/lib/python3.8/site-packages/cblaster/classes.py", line 256, in add_clusters    for subjects in subject_lists:  File "/home/phillip/miniconda3/lib/python3.8/site-packages/cblaster/context.py", line 370, in find_clusters    first = sorted_subjects.pop(0)IndexError: pop from empty list

I'm not sure what's going on here.  Any ideas how I can proceed?

**Comment by pksun1** [comment]
oh, and I'm doing this in Linux Mint Cinnamon OS, cblaster = version 1.3.12

**Comment by gamcil** [comment]
Seems like it's not detecting any clusters in the file for some reason. Is it possible to upload your session file so I could take a look? In the meantime you could try using the [CAGECAT](https://cagecat.bioinformatics.nl/) webserver instead of the GUI.

**Comment by pksun1** [comment]
Hi!  

Unfortunately I've since deleted the session file because I generated a lot of files when troubleshooting.  However I did manage to get past this problem in both command line and gui.  

The main issue I found is that I can only initiate clinker and gne modules with my json file output from search module only when using remote mode.  Cblaster search would download the genomic coordinates of the gene clusters (-ig in command line) in remote search only, and this would create the list of clusters in the resulting json output.  Unfortunately the -ig option doesn't seem to be available or otherwise functioning for local, hmm, and combi_local and combi_remote and thus no gene clusters are detected.  Is this a bug or is it maybe an upcoming function that is still in development?  I'd love to be able to smoothly use cblaster search json outputs and graph them with clinker, gne, especially with the combi_local and combi_remote search mode.  

Thanks,
Phillip
