### ISSUE TITLE
Error during "Fetching genomic context"

### ISSUE THREAD

**Issue by Adwaith99** [gamcil/cblaster#84]
In the version, 1.3.15, I am getting the error as shown below.

Importing genomicsqlite failed, falling back to SQLite3
[10:55:14] INFO - Starting cblaster in remote mode
[10:55:14] INFO - Launching new search
[10:55:15] INFO - Request Identifier (RID): NFY6JRSY013
[10:55:15] INFO - Request Time Of Execution (RTOE): 30s
[10:55:45] INFO - Polling NCBI for completion status
[10:55:45] INFO - Checking search status...
[10:56:45] INFO - Checking search status...
[10:57:45] INFO - Checking search status...
[10:58:45] INFO - Checking search status...
[10:59:45] INFO - Checking search status...
[11:00:45] INFO - Checking search status...
[11:01:45] INFO - Checking search status...
[11:01:45] INFO - Search has completed successfully!
[11:01:45] INFO - Retrieving results for search NFY6JRSY013
[11:06:32] INFO - Parsing results...
[11:06:32] INFO - Found 13382 hits meeting score thresholds for remote search
[11:06:32] INFO - Fetching genomic context of hits
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\adwai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\cblaster.exe\__main__.py", line 7, in <module>
  File "C:\Users\adwai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cblaster\main.py", line 432, in main
    cblaster(
  File "C:\Users\adwai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cblaster\main.py", line 334, in cblaster
    organisms = context.search(
  File "C:\Users\adwai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cblaster\context.py", line 591, in search
    rows = efetch_IPGs(
  File "C:\Users\adwai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cblaster\context.py", line 91, in efetch_IPGs
    if handle.code != 200:
AttributeError: '_io.TextIOWrapper' object has no attribute 'code'. Did you mean: 'close'?

**Comment by gamcil** [comment]
I'm having the same issue, it looks like there is a problem on the NCBI's side (E-utilities request for identical proteins is returning GenBank records...). Might just have to wait a little bit for it to be resolved unfortunately

**Comment by Adwaith99** [comment]
Hi, 
Just wanted to confirm, the error still has not been resolved right?

Thank you

**Comment by gamcil** [comment]
Should be resolved as of the new release which should be available now (https://github.com/gamcil/cblaster/releases/tag/v1.3.16). Could you try it out and see if it is working for you?

**Comment by Adwaith99** [comment]
Hi, 
It is working now. Thank you so much. @gamcil
