### ISSUE TITLE
makedb always results in 'sqlite3.OperationalError: database is locked'

### ISSUE THREAD

**Issue by jjsanchezgil** [gamcil/cblaster#89]
Hi,

I have been trying to create a local database but sqlite3 keeps showing this error. In my folder I have 3 files: genomic.fasta, genomic.gff, and genomic.gbff, but it doesn't matter if you try to build a database with only one file, like in this case, or with thousands, and either from gff or gbff. I tried installing cblaster from conda and with pip, but still the same error. What could be the source of the problem? Thanks

`$ cblaster makedb -n test genomic.gff`

[12:06:13] INFO - Starting makedb module
[12:06:13] INFO - Initialising cblaster SQLite3 database to test.sqlite3
Traceback (most recent call last):
  File "/opt/conda/anaconda3/envs/cblaster-env/bin/cblaster", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/anaconda3/envs/cblaster-env/lib/python3.8/site-packages/cblaster/main.py", line 422, in main
    database.makedb(
  File "/opt/conda/anaconda3/envs/cblaster-env/lib/python3.8/site-packages/cblaster/database.py", line 180, in makedb
    init_sqlite_db(sqlite_path, force=force)
  File "/opt/conda/anaconda3/envs/cblaster-env/lib/python3.8/site-packages/cblaster/database.py", line 39, in init_sqlite_db
    con.executescript(sql.SCHEMA)
sqlite3.OperationalError: database is locked

**Comment by gamcil** [comment]
Not sure what is happening unfortunately, I haven't run into this and can't reproduce it. Usually this error would come from something also interacting with the SQLite database file at the same time (e.g. via a DB browser/through the terminal). Maybe you have some rogue process in the background causing it to lock (https://stackoverflow.com/a/3481134)?

**Comment by mcn3159** [comment]
Hi, any chance someone solved this issue? I'm getting the same error regarding sqlite being unable to open database file.
