### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by yye88** [gamcil/cblaster#90]
Dear author, I have run many successful analysis of cblaster, and it is great. However, this time, when I started the routine process, something went wrong. The binary and json results were successfully obtained, but the error came out as shown below:

[11:11:10] INFO - Writing current search session to /ssd1/yye/data/cblaster-working/ere/AS_spo/sessionSpo.json
[11:11:14] INFO - Writing binary summary table to /ssd1/yye/data/cblaster-working/ere/AS_spo/binarySpo.txt
[11:11:14] INFO - Writing summary to /ssd1/yye/data/cblaster-working/ere/AS_spo/summarySpo.result
Traceback (most recent call last):
  File "/home/yye/.local/bin//cblaster", line 10, in <module>
    sys.exit(main())
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/main.py", line 469, in main
    testing=args.testing,
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/main.py", line 378, in cblaster
    sort_clusters=output_sort_clusters,
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/classes.py", line 146, in format
    table = summary(self, **kwargs)
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 248, in summary
    separator="\n\n\n",
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 126, in _summarise
    block = block_fn(item, **kwargs)
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 145, in summarise_organism
    separator="\n\n",
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 126, in _summarise
    block = block_fn(item, **kwargs)
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 156, in summarise_scaffold
    decimals=decimals,
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 126, in _summarise
    block = block_fn(item, **kwargs)
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 206, in summarise_cluster
    rows = humanise(rows)
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 25, in humanise
    table = add_field_whitespace(rows, lengths)
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 17, in add_field_whitespace
    fmt = [f"{row[index]:{length}}" for index, length in enumerate(lengths)]
  File "/home/yye/.local/lib/python3.7/site-packages/cblaster/formatters.py", line 17, in <listcomp>
    fmt = [f"{row[index]:{length}}" for index, length in enumerate(lengths)]
TypeError: unsupported format string passed to NoneType.__format__
[1]+  Exit 1                  nohup cblaster search -qf AS_protein.faa -o summarySpo.result -b binarySpo.txt -s sessionSpo.json -p plotSpo.html -r asy4 asy8 asy7 -ig

Could you please help me how to solve this problem? Thank you.

**Comment by gamcil** [comment]
Not sure, could you please upload the session file so I could take a look?

**Comment by yye88** [comment]
[sessionSpo.zip](https://github.com/gamcil/cblaster/files/10695290/sessionSpo.zip)
Sure, please take a look at it, thank you!

**Comment by gamcil** [comment]
Looks like it's tripping up when an intermediate gene had no ID - will have a fix for the next release.

**Comment by yye88** [comment]
Oh, cool, that will be nice! Thank you very much.

**Comment by gamcil** [comment]
This should be fixed in cblaster v1.3.18, which is out now.
