### ISSUE TITLE
cblaster didn't create .dmnd out file???????

### ISSUE THREAD

**Issue by neelam19051** [gamcil/cblaster#91]
Hi, i am running cblaster and it didn't create .dmnd diamond, however it only create sqlite3 and fasta file. if anyone know anything please let me know. It will be great help.

cblaster makedb -n localD -f   $(ls ~/Neelam/43_strains_gbk/*.gbk)
[18:20:39] INFO - Starting makedb module
[18:20:39] INFO - Pre-existing files found, overwriting
[18:20:39] INFO - Overwriting pre-existing file at localD.sqlite3
[18:20:39] INFO - Parsing 44 genome files, in 1 batches of 44
[18:20:39] INFO - Processing batch 1
[18:20:39] INFO -   P_aeruginosa_AR_0110.gbk
[18:20:39] INFO -   P_aeruginosa_AR_0111.gbk
[18:20:39] INFO -   P_aeruginosa_AR_455.gbk
[18:20:39] INFO -   P_aeruginosa_ATCC_15692.gbk
[18:20:39] INFO -   P_aeruginosa_ATCC_27853.gbk
[18:20:39] INFO -   P_aeruginosa_CMCP_115.gbk
[18:20:39] INFO -   P_aeruginosa_Cu1510.gbk
[18:20:39] INFO -   P_aeruginosa_DHS01.gbk
[18:20:39] INFO -   P_aeruginosa_DK2.gbk
[18:20:39] INFO -   P_aeruginosa_DVT419.gbk
[18:20:39] INFO -   P_aeruginosa_DVT421.gbk
[18:20:39] INFO -   P_aeruginosa_DVT425.gbk
[18:20:39] INFO -   P_aeruginosa_E90.gbk
[18:20:39] INFO -   P_aeruginosa_F5677.gbk
[18:20:39] INFO -   P_aeruginosa_FDAARGOS_1041.gbk
[18:20:39] INFO -   P_aeruginosa_FDAARGOS_532.gbk
[18:20:39] INFO -   P_aeruginosa_FDAARGOS_767.gbk
[18:20:39] INFO -   P_aeruginosa_GIMC5015_PAKB6.gbk
[18:20:39] INFO -   P_aeruginosa_HOU1.gbk
[18:20:39] INFO -   P_aeruginosa_LIUYANGP_C.gbk
[18:20:39] INFO -   P_aeruginosa_M1608.gbk
[18:20:39] INFO -   P_aeruginosa_NCTC12903.gbk
[18:20:39] INFO -   P_aeruginosa_NCTC13618.gbk
[18:20:39] INFO -   P_aeruginosa_NCTC13620.gbk
[18:20:39] INFO -   P_aeruginosa_NDTH10366.gbk
[18:20:39] INFO -   P_aeruginosa_PA0750.gbk
[18:20:39] INFO -   P_aeruginosa_PA1.gbk
[18:20:39] INFO -   P_aeruginosa_PA1R.gbk
[18:20:39] INFO -   P_aeruginosa_PA1RG.gbk
[18:20:39] INFO -   P_aeruginosa_PAO1.gbk
[18:20:39] INFO -   P_aeruginosa_PB353.gbk
[18:20:39] INFO -   P_aeruginosa_PB369.gbk
[18:20:39] INFO -   P_aeruginosa_QZPH21.gbk
[18:20:39] INFO -   P_aeruginosa_SCAID_PLC1P_2021_16_222.gbk
[18:20:39] INFO -   P_aeruginosa_SCAID_TSTP_2021_7_157.gbk
[18:20:39] INFO -   P_aeruginosa_SE5357.gbk
[18:20:39] INFO -   P_aeruginosa_SRRSH1101.gbk
[18:20:39] INFO -   P_aeruginosa_TL3773.gbk
[18:20:39] INFO -   P_aeruginosa_UNC_PaerCF05.gbk
[18:20:39] INFO -   P_aeruginosa_UNC_PaerCF14.gbk
[18:20:39] INFO -   P_aeruginosa_UNC_PaerCF17.gbk
[18:20:39] INFO -   P_aeruginosa_VRFPA04.gbk
[18:20:39] INFO -   P_aeruginosa_Y71.gbk
[18:20:39] INFO -   P_aeruginosa_Y89.gbk
[18:20:41] INFO - Saving 269318 genes
[18:20:43] INFO - Writing FASTA to localD.fasta
[18:20:44] INFO - Building DIAMOND database at localD.dmnd
[18:20:44] INFO - Done!

This two file only created.
localD.sqlite3 and 
localD.fasta  

Thank you !

**Comment by neelam19051** [comment]
Hi @gamcil , please reply if possible its urgent . i am facing this issue regarding cblaster local search-
cblaster search -m local -db mydb.dmnd -qf ~/Neelam/output12type.fasta 
[19:03:06] INFO - Starting cblaster in local mode
[19:03:08] INFO - Found 6740 hits meeting score thresholds for local search
[19:03:08] INFO - Fetching genomic context of hits
[19:03:08] INFO - Querying local SQLite3 database: /home/bvs/Neelam/cblaster_input/mydb.sqlite3
Traceback (most recent call last):
  File "/home/bvs/.local/bin/cblaster", line 8, in <module>
    sys.exit(main())
  File "/home/bvs/.local/lib/python3.8/site-packages/cblaster/main.py", line 432, in main
    cblaster(
  File "/home/bvs/.local/lib/python3.8/site-packages/cblaster/main.py", line 300, in cblaster
    organisms = context.search(
  File "/home/bvs/.local/lib/python3.8/site-packages/cblaster/context.py", line 591, in search
    organisms = query_local_DB(hits, sqlite_db)
  File "/home/bvs/.local/lib/python3.8/site-packages/cblaster/context.py", line 302, in query_local_DB
    ) in database.query_genes(list(hit_dict), db):
  File "/home/bvs/.local/lib/python3.8/site-packages/cblaster/database.py", line 104, in query_genes
    return _query(query, database)
  File "/home/bvs/.local/lib/python3.8/site-packages/cblaster/database.py", line 83, in _query
    query = cur.execute(query, values) if values else cur.execute(query)
**sqlite3.OperationalError: no such column: NECIECAO_04165**



thank you !

**Comment by gamcil** [comment]
Can you upload any of the files you used here? I downloaded some P. aeruginosa genomes from the NCBI and did not have any issues making/searching a local database with them. Are you on the newest version of cblaster?

**Comment by neelam19051** [comment]
Hi, @gamcil. Yes i am using latest version 1.3.18 and i have also check on NCBI file which accession number is GCF_000006765.1 but what i have found that .dmnd file isn't made by cblaster for this accession number of genome i.e PAO1 however when i used bua.gbk file as input cblaster  work perfectly fine, i mean it made .dmnd file and sqlite3, fasta all three. Sorry i am new here and i don't know how to upload gbk file here. I am searching how to do it whenever i will get solution then i'll upload my files.

Thank you for your time!

**Comment by Tim-Kirkwood** [comment]
Hi, might be way off here, but your dmnd file could be getting saved in a different folder to the one you expect (it's the only one without a filepath).  Try looking in your main user folder (C:\) or searching for 'localD' in you base directory.

**Comment by corkdagga** [comment]
Hi,

I am having the exact same problem as the first message. 

I am using both .gbff files created from Bakta or downloaded directly from NCBI (and have tried each individually with the same result) to create a database using the makedb tool. However, only the .sqlite3 and .fasta files are created and the .dmnd file is missing.

I have searched the entire hard drive for the .dmnd file and it is not placed elsewhere.
I have installed diamond (v4.0.515) before installing cblaster (v1.3.18)
Everything else seems to be working correctly.

Any help solving this issue would be great!

**Comment by hebalkaya** [comment]
Replying to @neelam19051: I have recently encountered this issue. It seems that when diamond is not (properly) installed on your working environment, cblaster will not produce the .dmnd (diamond) file and also won't raise any errors. That's why it is hard to debug this issue.

You can simply fix it by installing diamond with pip install.

This did the trick for me. I hope it will help others too.

**Comment by gamcil** [comment]
Thanks for the tip @hebalkaya, looks like cblaster needs a more robust check for the correct diamond. The ['diamond' available from PyPI](https://pypi.org/project/diamond/) is not related to the diamond aligner, but cblaster only looks for something named diamond/diamond-aligner on the system $PATH so it isn't catching this case correctly. In the meantime, installing diamond from the [repo](https://github.com/bbuchfink/diamond) or via conda/homebrew/etc should solve this issue.

**Comment by Changwanseo** [comment]
I found something realy strange about this

If you see my video, nearby 10s (at the left windows file directory), you can see that .dmnd file actually generated and deleted suddenly disappeared

The command that I used was

```
cblaster makedb -cp 4 -n Sanghuangporus -f ./genomes/*.gbk
```
I think this can be clue to what is happening

https://github.com/gamcil/cblaster/assets/64393882/c1321321-37f8-4813-b809-a6fcfcb5697c

**Comment by misha-baz** [comment]
Thank you for the insight, @Changwanseo ! I am encountering the same problem and I have ~200 genomes, unsure of how to check whether they are invalid, as they all look okay to me. MakeDB works completely fine for a different set of files, so it is specific to this dataset. Do you remember what exactly was wrong about the invalid file? Would be extremely helpful! Thank you!

**Comment by Changwanseo** [comment]
@misha-baz 
Sorry, but it was long time ago so I don't have memory about that.
I looked into the previous files, but I only have fixed version of the file. 
Sorry for inconvenience.

**Comment by misha-baz** [comment]
That's alright @Changwanseo , thanks for going through the trouble! I ended up singling out the faulty file through a process of painful elimination. I am not smart enough to figure out what is wrong with these, but I attached them here in case someone else is!

[GCF_029691745.1.gff3.txt](https://github.com/user-attachments/files/29136022/GCF_029691745.1.gff3.txt)
[GCF_029691745.1.fasta.txt](https://github.com/user-attachments/files/29136021/GCF_029691745.1.fasta.txt)
